=== openlibraryenvironment/mod-rs/service/src/main/resources/xsd/ISO-18626-v1_2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Written by: Ed Davidson (OCLC), Schema validated using XMLPad v3.0.2.1 (Build 07/05/2008) -->
<!-- ...................................... -->
<!-- ISO 18626 "Inter Library Loan Protocol -->
<!-- ...................................... -->
<!--
	Purpose: XML schema for ILL protocol ISO 18626
	Dependencies: None
	Change History:
		Version 1.2 November 2017
			Changed in order to describe the 2017 Minor revision of the standard
			Added the following four new data elements
				header
					multipleItemRequestId
				serviceType
					requestSubType
					startDate
					endDate
		Version 1.1 March 2014
			Changed the way enumerations were defined so that they would build correctly when using JAXB
			This file describes 2014 version of the standard
		Version 1.0 2014
			First Cut
 -->

 <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://illtransactions.org/2013/iso18626" targetNamespace="http://illtransactions.org/2013/iso18626" elementFormDefault="qualified" attributeFormDefault="qualified">
	<xs:element name="ISO18626Message">
		<xs:complexType>
			<xs:sequence>
				<xs:choice>
					<xs:element ref="request"/>
					<xs:element ref="requestConfirmation"/>
					<xs:element ref="supplyingAgencyMessage"/>
					<xs:element ref="supplyingAgencyMessageConfirmation"/>
					<xs:element ref="requestingAgencyMessage"/>
					<xs:element ref="requestingAgencyMessageConfirmation"/>
				</xs:choice>
			</xs:sequence>
			<xs:attribute name="version" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>

<!-- ............................ -->
<!-- Top Level Message Structures -->
<!-- ............................ -->

	<xs:element name="request">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="header"/>
				<xs:element ref="bibliographicInfo"/>
				<xs:element ref="publicationInfo" minOccurs="0"/>
				<xs:element ref="serviceInfo" minOccurs="0"/>
				<xs:element ref="supplierInfo" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="requestedDeliveryInfo" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="requestingAgencyInfo" minOccurs="0"/>
				<xs:element ref="patronInfo" minOccurs="0"/>
				<xs:element ref="billingInfo" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="requestConfirmation">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="confirmationHeader"/>
				<xs:element ref="errorData" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="supplyingAgencyMessage">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="header"/>
				<xs:element ref="messageInfo"/>
				<xs:element ref="statusInfo"/>
				<xs:element ref="deliveryInfo" minOccurs="0"/>
				<xs:element ref="returnInfo" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="supplyingAgencyMessageConfirmation">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="confirmationHeader"/>
				<xs:element name="reasonForMessage" type="type_reasonForMessage" minOccurs="0"/>
				<xs:element ref="errorData" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="requestingAgencyMessage">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="header"/>
				<xs:element name="action" type="type_action"/>
				<xs:element name="note" type="xs:string" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="requestingAgencyMessageConfirmation">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="confirmationHeader"/>
				<xs:element name="action" type="type_action" minOccurs="0"/>
				<xs:element ref="errorData" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
<!-- ................... -->	
<!-- Local Data Elements -->
<!-- ................... -->	

	<xs:element name="address">
		<xs:complexType>
			<xs:sequence>
				<xs:choice>
					<xs:element ref="electronicAddress"/>
					<xs:element ref="physicalAddress"/>
				</xs:choice>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="bibliographicItemId">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="bibliographicItemIdentifier" type="xs:string"/>
				<xs:element name="bibliographicItemIdentifierCode" type="type_schemeValuePair"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="bibliographicInfo">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="supplierUniqueRecordId" type="xs:string" minOccurs="0"/>
				<xs:element name="title" type="xs:string" minOccurs="0"/>
				<xs:element name="author" type="xs:string" minOccurs="0"/>
				<xs:element name="subtitle" type="xs:string" minOccurs="0"/>
				<xs:element name="seriesTitle" type="xs:string" minOccurs="0"/>
				<xs:element name="edition" type="xs:string" minOccurs="0"/>
				<xs:element name="titleOfComponent" type="xs:string" minOccurs="0"/>
				<xs:element name="authorOfComponent" type="xs:string" minOccurs="0"/>
				<xs:element name="volume" type="xs:string" minOccurs="0"/>
				<xs:element name="issue" type="xs:string" minOccurs="0"/>
				<xs:element name="pagesRequested" type="xs:string" minOccurs="0"/>
				<xs:element name="estimatedNoPages" type="xs:string" minOccurs="0"/>
				<xs:element ref="bibliographicItemId" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="sponsor" type="xs:string" minOccurs="0"/>
				<xs:element name="informationSource" type="xs:string" minOccurs="0"/>
				<xs:element ref="bibliographicRecordId" minOccurs="0" maxOccurs="unbounded"/> 
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="bibliographicRecordId">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="bibliographicRecordIdentifierCode" type="type_schemeValuePair"/>
				<xs:element name="bibliographicRecordIdentifier" type="xs:string"/>
			</xs:sequence>	
		</xs:complexType>
	</xs:element>	

	<xs:element name="billingInfo">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="paymentMethod" type="type_schemeValuePair" minOccurs="0"/>
				<xs:element name="maximumCosts" type="type_costs" minOccurs="0"/>
				<xs:element name="billingMethod" type="type_schemeValuePair" minOccurs="0"/>
				<xs:element name="billingName" type="xs:string" minOccurs="0"/>
				<xs:element ref="address" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="confirmationHeader">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="supplyingAgencyId" minOccurs="0"/>
				<xs:element ref="requestingAgencyId" minOccurs="0"/>
				<xs:element ref="timestamp"/>
				<xs:element ref="requestingAgencyRequestId" minOccurs="0"/>
				<xs:element ref="multipleItemRequestId" minOccurs="0"/>
				<xs:element ref="timestampReceived"/>
				<xs:element name="messageStatus" type="type_messageStatus"/>
		</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="deliveryInfo">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="dateSent" type="xs:dateTime"/>
				<xs:element name="itemId" type="xs:string" minOccurs="0"/> 
				<xs:element name="sentVia" type="type_schemeValuePair" minOccurs="0"/> 
				<xs:element name="sentToPatron" type="xs:boolean" minOccurs="0"/>
				<xs:element name="loanCondition" type="type_schemeValuePair" minOccurs="0"/>
				<xs:element name="deliveredFormat" type="type_schemeValuePair" minOccurs="0"/>
				<xs:element name="deliveryCosts" type="type_costs" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>	

	<xs:element name="electronicAddress">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="electronicAddressType" type="type_schemeValuePair"/>
				<xs:element name="electronicAddressData" type="xs:string"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="errorData">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="errorType" type="type_errorType"/>
				<xs:element name="errorValue" type="xs:string" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	

	<xs:element name="header">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="supplyingAgencyId"/>
				<xs:element ref="requestingAgencyId"/>
				<xs:element ref="multipleItemRequestId"/>
				<xs:element ref="timestamp"/>
				<xs:element ref="requestingAgencyRequestId"/>
				<xs:element ref="supplyingAgencyRequestId" minOccurs="0"/>
				<xs:element ref="requestingAgencyAuthentication" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="messageInfo">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="reasonForMessage" type="type_reasonForMessage"/>
				<xs:element name="answerYesNo" type="type_yesNo" minOccurs="0"/>
				<xs:element name="note" type="xs:string" minOccurs="0"/>
				<xs:element name="reasonUnfilled" type="type_schemeValuePair" minOccurs="0"/>
				<xs:element name="reasonRetry" type="type_schemeValuePair" minOccurs="0"/>
				<xs:element name="offeredCosts" type="type_costs" minOccurs="0"/>
				<xs:element name="retryAfter" type="xs:dateTime" minOccurs="0"/>
				<xs:element name="retryBefore" type="xs:dateTime" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>	
	
	<xs:element name="multipleItemRequestId" type="xs:string"/>
	
	<xs:element name="patronInfo">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="patronId" type="xs:string" minOccurs="0"/> 
				<xs:element name="surname" type="xs:string" minOccurs="0"/>
				<xs:element name="givenName" type="xs:string" minOccurs="0"/>
				<xs:element name="patronType" type="type_schemeValuePair" minOccurs="0"/>
				<xs:element name="sendToPatron" type="type_yesNo" minOccurs="0"/> 
				<xs:element ref="address" minOccurs="0" maxOccurs="unbounded"/>		
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="physicalAddress">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="line1" type="xs:string" minOccurs="0"/>
				<xs:element name="line2" type="xs:string" minOccurs="0"/>
				<xs:element name="locality" type="xs:string" minOccurs="0"/>
				<xs:element name="postalCode" type="xs:string" minOccurs="0"/>
				<xs:element name="region" type="type_schemeValuePair" minOccurs="0"/> 	<!-- ISO 3166-2 --> 
				<xs:element name="country" type="type_schemeValuePair" minOccurs="0"/>	<!-- ISO 3166-1 -->
			</xs:sequence>
		</xs:complexType>
	</xs:element>	
	
	<xs:element name="publicationInfo">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="publisher" type="xs:string" minOccurs="0"/>
				<xs:element name="publicationType" type="type_schemeValuePair" minOccurs="0"/>
				<xs:element name="publicationDate" type="xs:string" minOccurs="0"/>
				<xs:element name="placeOfPublication" type="xs:string" minOccurs="0"/>
				</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="requestedDeliveryInfo">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="sortOrder" type="xs:integer" minOccurs="0"/>
				<xs:element ref="address" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="requestingAgencyAuthentication">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="accountId" type="xs:string" minOccurs="0"/>
				<xs:element name="securityCode" type="xs:string" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="requestingAgencyId" type="type_agencyId"/>	

	<xs:element name="requestingAgencyInfo">
	<xs:complexType>
			<xs:sequence>
				<xs:element name="name" type="xs:string" minOccurs="0"/>
				<xs:element name="contactName" type="xs:string" minOccurs="0"/>
				<xs:element ref="address" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="requestingAgencyRequestId" type="xs:string"/>
	
	<xs:element name="returnInfo">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="returnAgencyId" type="type_agencyId" minOccurs="0"/>
				<xs:element name="name" type="xs:string" minOccurs="0"/>
				<xs:element ref="physicalAddress" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>	

	<xs:element name="serviceInfo">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="requestType" type="type_requestType" minOccurs="0"/>
				<xs:element name="requestSubType" type="type_requestSubType" minOccurs="0" maxOccurs="3"/>
				<xs:element name="requestingAgencyPreviousRequestId" type="xs:string" minOccurs="0"/>
				<xs:element name="serviceType" type="type_serviceType"/>
				<xs:element name="serviceLevel" type="type_schemeValuePair" minOccurs="0"/>
				<xs:element name="preferredFormat" type="type_schemeValuePair" minOccurs="0"/>
				<xs:element name="needBeforeDate" type="xs:dateTime" minOccurs="0"/>
				<xs:element name="copyrightCompliance" type="type_schemeValuePair" minOccurs="0"/>
				<xs:element name="anyEdition" type="type_yesNo" minOccurs="0"/> 
				<xs:element name="startDate" type="xs:dateTime" minOccurs="0"/>
				<xs:element name="endDate" type="xs:dateTime" minOccurs="0"/>
				<xs:element name="note" type="xs:string" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
		
	<xs:element name="statusInfo">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="status" type="type_status"/>
				<xs:element name="expectedDeliveryDate" type="xs:dateTime" minOccurs="0"/>
				<xs:element name="dueDate" type="xs:dateTime" minOccurs="0"/>
				<xs:element name="lastChange" type="xs:dateTime"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="supplierInfo">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="sortOrder" type="xs:integer" minOccurs="0"/>
				<xs:element name="supplierCode" type="type_agencyId" minOccurs="0"/>
				<xs:element name="supplierDescription" type="xs:string" minOccurs="0"/>
				<xs:element ref="bibliographicRecordId" minOccurs="0"/>
				<xs:element name="callNumber" type="xs:string" minOccurs="0"/>
				<xs:element name="summaryHoldings" type="xs:string" minOccurs="0"/> 
				<xs:element name="availabilityNote" type="xs:string" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="supplyingAgencyId" type="type_agencyId"/>	

	<xs:element name="supplyingAgencyRequestId" type="xs:string"/>

	<xs:element name="timestamp" type="xs:dateTime"/>
	
	<xs:element name="timestampReceived" type="xs:dateTime"/>
	
<!-- ............. -->		
<!-- Complex Types -->
<!-- ............. -->


	<xs:simpleType name="type_action">
		<xs:restriction base="xs:string">
			<xs:enumeration value="StatusRequest"/>
			<xs:enumeration value="Received"/>
			<xs:enumeration value="Cancel"/>
			<xs:enumeration value="Renew"/>
			<xs:enumeration value="ShippedReturn"/>
			<xs:enumeration value="ShippedForward"/>
			<xs:enumeration value="Notification"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="type_agencyId">
		<xs:sequence>
			<xs:element name="agencyIdType" type="type_schemeValuePair"/>
			<xs:element name="agencyIdValue" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="type_costs">
		<xs:sequence>
			<xs:element name="currencyCode" type="type_schemeValuePair"/><!--ISO 4217 -->
			<xs:element name="monetaryValue" type="xs:decimal"/>
		</xs:sequence>	
	</xs:complexType>

	<xs:simpleType name="type_errorType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="UnsupportedActionType"/>
			<xs:enumeration value="UnsupportedReasonForMessageType"/>
			<xs:enumeration value="UnrecognisedDataElement"/>
			<xs:enumeration value="UnrecognisedDataValue"/>
			<xs:enumeration value="BadlyFormedMessage"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="type_messageStatus">
		<xs:restriction base="xs:string">
			<xs:enumeration value="OK"/>
			<xs:enumeration value="ERROR"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="type_reasonForMessage">
		<xs:restriction base="xs:string">
			<xs:enumeration value="RequestResponse"/>
			<xs:enumeration value="StatusRequestResponse"/>
			<xs:enumeration value="RenewResponse"/>
			<xs:enumeration value="CancelResponse"/>
			<xs:enumeration value="StatusChange"/>
			<xs:enumeration value="Notification"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="type_requestType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="New"/>
			<xs:enumeration value="Retry"/>
			<xs:enumeration value="Reminder"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="type_requestSubType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="BookingRequest"/>
			<xs:enumeration value="MultipleItemRequest"/>
			<xs:enumeration value="PatronRequest"/>
			<xs:enumeration value="TransferRequest"/>
			<xs:enumeration value="SupplyingLibrarysChoice"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:complexType name="type_schemeValuePair">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="scheme" type="xs:anyURI"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:simpleType name="type_serviceType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Copy"/>
			<xs:enumeration value="Loan"/>
			<xs:enumeration value="CopyOrLoan"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="type_status">
		<xs:restriction base="xs:string">
			<xs:enumeration value="RequestReceived"/>
			<xs:enumeration value="ExpectToSupply"/>
			<xs:enumeration value="WillSupply"/>
			<xs:enumeration value="Loaned"/>
			<xs:enumeration value="Overdue"/>
			<xs:enumeration value="Recalled"/>
			<xs:enumeration value="RetryPossible"/>
			<xs:enumeration value="Unfilled"/>
			<xs:enumeration value="CopyCompleted"/>
			<xs:enumeration value="LoanCompleted"/>
			<xs:enumeration value="CompletedWithoutReturn"/>
			<xs:enumeration value="Cancelled"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="type_yesNo">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Y"/>
			<xs:enumeration value="N"/>
		</xs:restriction>
	</xs:simpleType>
	
</xs:schema>

=== openlibraryenvironment/mod-rs/service/src/integration-test/resources/isoMessages/illmockrequest.xml
<ISO18626Message xmlns="http://illtransactions.org/2013/iso18626"
                 xmlns:ill="http://illtransactions.org/2013/iso18626"
                 ill:version="1.2"
                 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:schemaLocation="http://illtransactions.org/2013/iso18626 http://illtransactions.org/schemas/ISO-18626-v1_2.xsd">
    <request>
        <header>
            <supplyingAgencyId>
                <agencyIdType>DMMY</agencyIdType>
                <agencyIdValue>NIA1</agencyIdValue>
            </supplyingAgencyId>
            <requestingAgencyId>
                <agencyIdType>DMMY</agencyIdType>
                <agencyIdValue>NIA2</agencyIdValue>
            </requestingAgencyId>
            <multipleItemRequestId></multipleItemRequestId>
            <timestamp>0001-01-01T00:00:00.000Z</timestamp>
            <requestingAgencyRequestId>DMMYNIA2-1</requestingAgencyRequestId>
        </header>
        <bibliographicInfo>
            <!--
              specify supplier scenario via <supplierUniqueRecordId> field, see https://github.com/indexdata/crosslink/blob/main/illmock/README.md#supplier-behavior
            -->
            <!--
              NOTE: when submitting a PatronRequest where the broker is the supplier peer (default),
              and assuming the broker is configured with the mock SRU holdings adapter (also default),
              you can specify multiple ILL scenarios for each mock supplier located by the broker with a semicolon separated list, e.g.:
               <supplierUniqueRecordId>ERROR;UNFILLED;WILLSUPPLY_UNFILLED;LOANED</supplierUniqueRecordId>
            -->
            <supplierUniqueRecordId>LOANED</supplierUniqueRecordId>
            <title>Layered of the Rungs</title>
            <author>Junior Tooken</author>
            <bibliographicItemId>
                <bibliographicItemIdentifier>1884</bibliographicItemIdentifier>
                <bibliographicItemIdentifierCode>ISBN</bibliographicItemIdentifierCode>
            </bibliographicItemId>
            <bibliographicRecordId>
                <bibliographicRecordIdentifierCode ill:scheme="RESHARE">patronReference</bibliographicRecordIdentifierCode>
                <bibliographicRecordIdentifier>ref-33-44-55</bibliographicRecordIdentifier>
            </bibliographicRecordId>
        </bibliographicInfo>
        <serviceInfo>
            <requestType>New</requestType>
            <!--
              use requestSubType:PatronRequest ONLY if the mock should act as a requester and send a request to the supplier peer (broker by default)
            -->
            <requestSubType>PatronRequest</requestSubType>
            <serviceType>Loan</serviceType>
            <!--
              specify requester behavior via the <note> field, see https://github.com/indexdata/crosslink/blob/main/illmock/README.md#requester-behavior
            -->
              <note>#CANCEL#</note>
        </serviceInfo>
        <!--
          optionally, supplier peer address can be specified below, otherwise the default (broker) is used
        -->
        <!--
        <supplierInfo>
          <supplierDescription>https://broker.crosslink-dev.indexdata.com/iso18626</supplierDescription>
        </supplierInfo>
        -->
        <!--
          optionally, requester peer address can be specified below, otherwise the default (broker) is used
        -->
        <!--
        <requestingAgencyInfo>
          <address>
            <electronicAddress>
              <electronicAddressType></electronicAddressType>
              <electronicAddressData>https://broker.crosslink-dev.indexdata.com/iso8626</electronicAddressData>
            </electronicAddress>
          </address>
        </requestingAgencyInfo>
        -->
    </request>
</ISO18626Message>

=== openlibraryenvironment/mod-rs/service/src/integration-test/resources/isoMessages/patronRequestRetry.xml
<ISO18626Message xmlns="http://illtransactions.org/2013/iso18626" ill:version="1.2" xmlns:ill="http://illtransactions.org/2013/iso18626" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://illtransactions.org/2013/iso18626 http://illtransactions.org/schemas/ISO-18626-v1_2.xsd">
    <request>
        <header>
            <requestingAgencyId>
                <agencyIdType scheme="">ISIL</agencyIdType>
                <agencyIdValue></agencyIdValue>
            </requestingAgencyId>
            <multipleItemRequestId></multipleItemRequestId>
            <timestamp>2023-11-16T12:32:11.056Z</timestamp>
            <requestingAgencyRequestId>requestId_holder</requestingAgencyRequestId>
        </header>
        <bibliographicInfo>
            <supplierUniqueRecordId>54321</supplierUniqueRecordId>
            <title>Lord of the Rings</title>
            <author>J.R.R. Tolkien</author>
            <authorId></authorId>
            <subtitle></subtitle>
            <seriesTitle></seriesTitle>
            <edition></edition>
            <titleOfComponent></titleOfComponent>
            <authorOfComponent></authorOfComponent>
            <issue></issue>
            <pagesRequested></pagesRequested>
            <estimatedNoPages></estimatedNoPages>
            <bibliographicItemId>
                <bibliographicItemIdentifierCode scheme="">ISBN</bibliographicItemIdentifierCode>
                <bibliographicItemIdentifier>12321312</bibliographicItemIdentifier>
            </bibliographicItemId>
            <bibliographicRecordId>
                <bibliographicRecordIdentifierCode ill:scheme="ZFL">TitelId</bibliographicRecordIdentifierCode>
                <bibliographicRecordIdentifier>in00000000002</bibliographicRecordIdentifier>
            </bibliographicRecordId>
            <bibliographicRecordId>
                <bibliographicRecordIdentifierCode ill:scheme="ZFL">BsTyp2</bibliographicRecordIdentifierCode>
                <bibliographicRecordIdentifier>L</bibliographicRecordIdentifier>
            </bibliographicRecordId>
            <bibliographicRecordId>
                <bibliographicRecordIdentifierCode ill:scheme="ZFL">MedTyp</bibliographicRecordIdentifierCode>
                <bibliographicRecordIdentifier>ml</bibliographicRecordIdentifier>
            </bibliographicRecordId>
            <sponsor></sponsor>
            <informationSource></informationSource>
        </bibliographicInfo>
        <serviceInfo>
            <requestType>Retry</requestType>
            <requestSubType>PatronRequest</requestSubType>
            <requestingAgencyPreviousRequestId></requestingAgencyPreviousRequestId>
            <serviceType>Loan</serviceType>
            <needBeforeDate></needBeforeDate>
            <startDate></startDate>
            <endDate></endDate>
            <note></note>
        </serviceInfo>
        <patronInfo>
            <patronId>patronId_holder</patronId>
            <surname></surname>
            <givenName></givenName>
        </patronInfo>
        <requestedDeliveryInfo>
            <address>
                <physicalAddress>
                    <line1>RSSlnpOne</line1>
                </physicalAddress>
            </address>
        </requestedDeliveryInfo>
    </request>
</ISO18626Message>

=== openlibraryenvironment/mod-rs/service/src/integration-test/resources/isoMessages/cancelResponseReplyNoTemplate.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ill:ISO18626Message ill:version="1.2" xsi:schemaLocation="http://illtransactions.org/2013/iso18626 https://illtransactions.org/schemas/ISO-18626-v1_2.xsd" xmlns:ill="http://illtransactions.org/2013/iso18626" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <ill:supplyingAgencyMessage>
        <ill:header>
            <ill:supplyingAgencyId>
                <ill:agencyIdType>ISIL</ill:agencyIdType>
                <ill:agencyIdValue>_SUPPLY_AGENCY_ID_</ill:agencyIdValue>
            </ill:supplyingAgencyId>
            <ill:requestingAgencyId>
                <ill:agencyIdType>ISIL</ill:agencyIdType>
                <ill:agencyIdValue>_REQUEST_AGENCY_ID_</ill:agencyIdValue>
            </ill:requestingAgencyId>
            <ill:multipleItemRequestId></ill:multipleItemRequestId>
            <ill:timestamp>_TIMESTAMP_</ill:timestamp>
            <ill:requestingAgencyRequestId>_REQUEST_ID_</ill:requestingAgencyRequestId>
            <ill:supplyingAgencyRequestId>_REQUEST_ID_</ill:supplyingAgencyRequestId>
        </ill:header>
        <ill:messageInfo>
            <ill:reasonForMessage>CancelResponse</ill:reasonForMessage>
            <ill:answerYesNo>N</ill:answerYesNo>
            <ill:reasonUnfilled></ill:reasonUnfilled>
            <ill:reasonRetry></ill:reasonRetry>
        </ill:messageInfo>
        <ill:deliveryInfo>
            <ill:dateSent>_TIMESTAMP_</ill:dateSent>
            <ill:sentToPatron>false</ill:sentToPatron>
            <ill:loanCondition></ill:loanCondition>
            <ill:deliveredFormat></ill:deliveredFormat>
        </ill:deliveryInfo>
        <ill:returnInfo></ill:returnInfo>
    </ill:supplyingAgencyMessage>
</ill:ISO18626Message>
